INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 1', 'Action', 'MOVIE', 100, 3.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 2', 'Drama', 'MOVIE', 50, 3.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 3', 'Comedy', 'MOVIE', 80, 3.5);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 1', 'Drama', 'SERIES', 150, 5.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 2', 'Comedy', 'SERIES', 90, 3.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 3', 'Action', 'SERIES', 120, 4.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 4', 'Thriller', 'MOVIE', 75, 4.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 4', 'Fantasy', 'SERIES', 110, 3.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 5', 'Horror', 'MOVIE', 60, 5.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 6', 'Science Fiction', 'MOVIE', 85, 4.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 5', 'Mystery', 'SERIES', 95, 3.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 6', 'Romance', 'SERIES', 130, 4.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 7', 'Adventure', 'MOVIE', 70, 4.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Movie 8', 'Action', 'MOVIE', 120, 5.0);
INSERT INTO `media_item`(`name`, `genre`, `type`, `views`, `rating`) VALUES ('Series 7', 'Drama', 'SERIES', 140, 3.0);


INSERT INTO rating (score, media_item_id) VALUES (4, 1);
INSERT INTO rating (score, media_item_id) VALUES (2, 1);
INSERT INTO rating (score, media_item_id) VALUES (3, 2);
INSERT INTO rating (score, media_item_id) VALUES (4, 3);
INSERT INTO rating (score, media_item_id) VALUES (5, 4);
INSERT INTO rating (score, media_item_id) VALUES (3, 5);
INSERT INTO rating (score, media_item_id) VALUES (4, 6);
INSERT INTO rating (score, media_item_id) VALUES (4, 7);
INSERT INTO rating (score, media_item_id) VALUES (3, 8);
INSERT INTO rating (score, media_item_id) VALUES (5, 9);
INSERT INTO rating (score, media_item_id) VALUES (4, 10);
INSERT INTO rating (score, media_item_id) VALUES (3, 11);
INSERT INTO rating (score, media_item_id) VALUES (4, 12);
INSERT INTO rating (score, media_item_id) VALUES (4, 13);
INSERT INTO rating (score, media_item_id) VALUES (5, 14);
INSERT INTO rating (score, media_item_id) VALUES (3, 15);
INSERT INTO rating (score, media_item_id) VALUES (3, 2);
INSERT INTO rating (score, media_item_id) VALUES (3, 3);